// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juzktwqpjyciugforehd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1emt0d3FwanljaXVnZm9yZWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTU4ODcsImV4cCI6MjA2MTE3MTg4N30.SCcmhYJ9TuRhRXffP_n4ntfpzLvZqwcxp-huaDBu1UM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);